spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  mvc:
    view:
      suffix: .ftl

  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl